add edit function
Wandersmann731/Shopping-buddy pull request #6
Opened 2024-09-16 08:11 UTC by Wandersmann731

2024-09-16 11:28 UTC, IsabellUrban reviewed
Hi, I found some things in your code. You use a lot of margin in your styled Components. In many layouts, using too much margin can cause unexpected results. Better use gap or padding instead. The styled components are missing the prefix "styled". We have learned this as a naming convention. For example: const StyledDeleteButton = styled.button`. We should not abbreviate event with e. In the course we wrote functions with function keyword and avoided arrow functions.

2024-09-16 11:28 UTC, IsabellUrban commented on pages/index.js
>    button {
You can't nest a button in a Button Component. This contradict the semantic html.

2024-09-16 12:35 UTC, NikRoe requested changes
Hi there,

nice start!

I left some suggestions for you to implement. Please also take a look at the comment from Isabell, since it contains some valuable feedback.

Keep it up 🙌

2024-09-16 12:35 UTC, NikRoe commented on pages/index.js
> +  // };
You should remove code you don't need:

```suggestion
```

2024-09-16 12:35 UTC, NikRoe commented on pages/index.js
> +  };
You don't need this function. Your button would also work if you gave it the attribute `type="reset"` and an `onClick` that only sets the `isFormVisible` state to `false`.

2024-09-16 12:35 UTC, NikRoe commented on pages/index.js
> +          <Button onClick={handleCancel}>Cancel</Button>
```suggestion
          <Button type="reset" onClick={() => setIsFormVisible(false)}>Cancel</Button>
```

2024-09-16 12:35 UTC, NikRoe commented on pages/index.js
> +  margin 10px;
```suggestion
  margin: 10px;
```

2024-09-16 12:35 UTC, NikRoe commented on pages/index.js
> +  margin 10px;
```suggestion
  margin: 10px;
```

2024-09-17 08:40 UTC, LorenzCoachK commented on pages/index.js
Please mark quantity as required and lay an errormessage if the user deletes the value in quantity.

2024-09-17 09:18 UTC, merged